"""Add watch_url to Movie

Revision ID: 688acf539814
Revises: bd69d4d77e12
Create Date: 2025-04-27 22:07:39.668897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '688acf539814'
down_revision = 'bd69d4d77e12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('watch_url', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_column('watch_url')

    # ### end Alembic commands ###
